//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aluno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aluno()
        {
            this.confirmareserva = new HashSet<confirmareserva>();
        }
    
        public int Pessoa_idPessoa { get; set; }
        public int idTurma { get; set; }
        public int MatSESI { get; set; }
        public Nullable<int> MatSENAI { get; set; }
    
        public virtual turma turma { get; set; }
        public virtual pessoa pessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<confirmareserva> confirmareserva { get; set; }
    }
}
