//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class avaliacao
    {
        public int idAvaliacao { get; set; }
        public int ConfirmaReserva_Aluno_Pessoa_idPessoa { get; set; }
        public int ConfirmaReserva_idConfirmaReserva { get; set; }
        public int Nota { get; set; }
        public string Observacao { get; set; }
    
        public virtual confirmareserva confirmareserva { get; set; }
    }
}
