//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTCC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class modelagemtcc_Entities : DbContext
    {
        public modelagemtcc_Entities()
            : base("name=modelagemtcc_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aluno> aluno { get; set; }
        public virtual DbSet<avaliacao> avaliacao { get; set; }
        public virtual DbSet<cardapio> cardapio { get; set; }
        public virtual DbSet<cargo> cargo { get; set; }
        public virtual DbSet<confirmareserva> confirmareserva { get; set; }
        public virtual DbSet<funcionario> funcionario { get; set; }
        public virtual DbSet<pessoa> pessoa { get; set; }
        public virtual DbSet<reserva> reserva { get; set; }
        public virtual DbSet<turma> turma { get; set; }
    }
}
