//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class confirmareserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public confirmareserva()
        {
            this.avaliacao = new HashSet<avaliacao>();
        }
    
        public int idConfirmaReserva { get; set; }
        public int Aluno_Pessoa_idPessoa { get; set; }
        public int idReserva { get; set; }
        public string DTConfReserva { get; set; }
        public string ConfPresente { get; set; }
    
        public virtual aluno aluno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<avaliacao> avaliacao { get; set; }
        public virtual reserva reserva { get; set; }
    }
}
