//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pessoa
    {
        public int idPessoa { get; set; }
        public string Nome { get; set; }
        public string Sobrenome { get; set; }
        public long CPF { get; set; }
        public string TipoPessoa { get; set; }
        public string Email { get; set; }
        public long Telefone { get; set; }
        public string Status { get; set; }
        public string Senha { get; set; }
    
        public virtual aluno aluno { get; set; }
        public virtual funcionario funcionario { get; set; }
    }
}
