//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppTCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reserva()
        {
            this.confirmareserva = new HashSet<confirmareserva>();
        }
    
        public int idReserva { get; set; }
        public int Funcionario_Pessoa_idPessoa { get; set; }
        public int idcardapio { get; set; }
        public int idTurma { get; set; }
        public string DTCadReserva { get; set; }
        public string StatusReserva { get; set; }
        public string DescricaoReserva { get; set; }
    
        public virtual cardapio cardapio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<confirmareserva> confirmareserva { get; set; }
        public virtual funcionario funcionario { get; set; }
        public virtual turma turma { get; set; }
    }
}
